version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=whatislove
    ports:
      - "5432:5432"

  server:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres